[default]
users_db = "users.db"
auth = "dangerous"
contrib = false
tools = []

[default.github_oauth]
client_id = ""
client_secret = ""
base_url = "http://localhost:8000"

[default.github_pat]
token = ""

[default.dangerous]

[default.logging]
version = 1
disable_existing_loggers = false

[default.logging.formatters.standard]
format = "%(levelname)s [%(name)s] %(message)s"

[default.logging.formatters.verbose]
format = "%(asctime)s %(levelname)s [%(name)s] %(message)s"

[default.logging.handlers.console]
class = "logging.StreamHandler"
formatter = "standard"

[default.logging.loggers.mcc]
level = "WARNING"
handlers = ["console"]
propagate = false

[development]
dynaconf_merge = true

[development.logging.loggers.mcc]
level = "DEBUG"

[production]
dynaconf_merge = true

[production.logging.handlers.console]
formatter = "verbose"

[production.logging.loggers.mcc]
level = "INFO"